version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: RO_mousion_DB_Design
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./data:/var/lib/mysql                   # Mount a volume for data persistence (optional)
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mousiondb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 2121:3306
      # application_port:host_port (3306:2121)
